# 设置网管端口，一般设置为9999，可以根据自己需求设置
server:
  port: 9999
#设置网管名称
spring:
  application:
    name: spcloud-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-to-baidu
          uri: http://www.baidu.com
          predicates:
          - Path=/baidu11111
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/gateway
            - StripPrefix=1
#设置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug
